In [1]:
import numpy as np

# Create two arrays
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Element-wise addition
sum_ab = a + b

# Element-wise multiplication
product_ab = a * b

# Mean and standard deviation
mean_a = np.mean(a)
std_a = np.std(a)

# Display results
print("Array A:", a)
print("Array B:", b)
print("Sum of A and B:", sum_ab)
print("Product of A and B:", product_ab)
print("Mean of A:", mean_a)
print("Standard Deviation of A:", std_a)


Array A: [1 2 3 4]
Array B: [5 6 7 8]
Sum of A and B: [ 6  8 10 12]
Product of A and B: [ 5 12 21 32]
Mean of A: 2.5
Standard Deviation of A: 1.118033988749895


In [2]:
np.array([1, 2, 3])           # Create from list
np.zeros((2, 3))              # Array of zeros
np.ones((2, 3))               # Array of ones
np.full((2, 3), 7)            # Filled with a specific value
np.eye(3)                     # Identity matrix
np.arange(0, 10, 2)           # Range with step
np.linspace(0, 1, 5)          # Evenly spaced numbers
np.random.rand(2, 2)          # Random values (uniform)
np.random.randn(2, 2)         # Random values (normal)


array([[ 1.57708874, -0.35976811],
       [ 0.77475142, -0.61801454]])

In [3]:
import numpy as np

# Step 1: Generate random scores for 5 students in 3 subjects (Math, Science, English)
np.random.seed(42)  # For reproducibility
scores = np.random.randint(50, 100, size=(5, 3))

# Step 2: Display scores
print("Student Scores (Math, Science, English):\n", scores)

# Step 3: Calculate average score per student
average_per_student = np.mean(scores, axis=1)
print("\nAverage Score Per Student:", average_per_student)

# Step 4: Calculate average score per subject
average_per_subject = np.mean(scores, axis=0)
print("Average Score Per Subject (Math, Science, English):", average_per_subject)

# Step 5: Find the top performer (student with highest average)
top_student_index = np.argmax(average_per_student)
print("Top Performer: Student", top_student_index + 1)

# Step 6: Find how many students scored above 90 in any subject
high_scores = scores > 90
students_with_90_plus = np.any(high_scores, axis=1)
count_90_plus = np.sum(students_with_90_plus)
print("Number of students with 90+ in any subject:", count_90_plus)


Student Scores (Math, Science, English):
 [[88 78 64]
 [92 57 70]
 [88 68 72]
 [60 60 73]
 [85 89 73]]

Average Score Per Student: [76.66666667 73.         76.         64.33333333 82.33333333]
Average Score Per Subject (Math, Science, English): [82.6 70.4 70.4]
Top Performer: Student 5
Number of students with 90+ in any subject: 1
